server:
  port: 9011

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 42.194.239.199:10242 #配置Nacos注册中心地址

management:
  endpoints:
    web:
      exposure:
        include: '*'

