server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9001          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/nacos1/**         # 断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://localhost:9002          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/nacos2/**        # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: 42.194.239.199:10242



